#+TITLE: The Big Picture
#+AUTHOR: <lngnmn2@yahoo.com>
#+STARTUP: indent fold overview

I am already a quite old guy, at least other people threat me as one. This means that I have tried (and failed) quite a lot of things, and have got in return something what they call "experience". At least I have read some, here and there.

When one "studies", lets say, Indian or Buddhist philosophy (well, this is a /vast/ subject) there is a distinct, recurring (again and again) common pattern -- the early intuitive and shared experience-based teachings (of the ancients) are getting systematically destroyed and transformed into incomprehensible verbiage vomit of abstract terminology.

All the "famous commentators" just introduced more and more "primitive" abstractions (which they think as refinements) and turned the teaching, pure and simple, into a scholastic shitfest. Moreover, most of them do not know when to stop, and are keeping producing more and more "spiritual" verbiage.

There is /always/, nowever, the end of a search, the end of knowledge, when the whole "maze" has been explored (and nothing more "real" that it itself has been found).

The rare insights of the Upanishads has been turned by "commentators" into abstract doctrines, the teaching of the Buddha has been turned into ritualistic mumbling, just like Brahmanas turned everything into endless sacrifice rituals.

You may think that such things (social movements which the pattern captures) happens only in the distant past, and now we are all rational and even "scientific" instead of speculative and too abstract. Hardly.

The early teachings of what we call "Computer Science" has been ruined and transformed (by "creative" idiots) into incomprehensible abstract bullshit in exactly the same way, turning everything into a syntactic vomit of unnecessary, redundant abstractions (which is the root of all evil).

This is not an exaggeration in the least. By the late 90s, with the emergence of the Haskell 98 standard (and the R5RS prior to it), as well as refinement of the ML (and then Ocaml) modules with functors, /everything/ out there has been well-understood. The abstract interfaces, a generalization of ADTs, and corresponding small modules which hide all the (representation and implementation) details, has been placed at the center of what a non-bullshit programming (the science of managing complexity) is really.

At least 3 distinct traditions has been emerged from the Simply-Typed Lambda Calculus and ISWIM -- the ones of SML/Ocaml, Scheme and the most notably, of Miranda/Haskell. Erlang and Scala emerged as schisms of their own.

There are a few distinct "patterns" which are common of all of these traditions -- a minimal subset of special forms in a mostly functional language which is good-enough (even optimal) for everything. Technically, the intermediate language of the Glasgow Haskell Compiler, which corresponds to the /System F Omega/, is that "core".

When one is looking at these special forms and is trying to draws the arrows between dots, one (if smart enough) would discover more distinct common patterns. These has been /partially/ captured by the algorithm charting techniques from the 70s.

Unsurprisingly, if we add /the structural pattern matching/ (on Algebraic Data Types), which all the ML tradition languages have, one will see "the complete picture" -- a better branching (more arrows going out). All the "special forms" are reducible to just a few universal patterns of "arrows between dots" (to which the Category Theory has arrived by another route).

Since the 90s, the smartest people (who gave us CLU, SML and Haskell) told us, that /this/ is good-enough for everything and even that /this/ is how to manage complexity and how to compute.

If one knows some very basic cell biology, one would see the very same patterns "Out There", just as the early LISP guys did (when freshly discovered the actual structure of DNA was a big deal).

And suddenly, someone like me, discovered that Monads in Haskell (which is, just a type-class for a simple ADT of a Monoidal composition) corresponds to a the notion of a universal abstraction barrier, or of a cell-membrane.

The really smart guys (around Odersky) were generalized the /for-comprehensions/ around Monadic composition, and this is where we are today.

Now, how many people have actually comprehended and realized all this? I know of no one else. You would be the first to learn all this from here.
