#+TITLE: Required Readings
#+AUTHOR: <lngnmn2@yahoo.com>
#+STARTUP: indent fold overview

The major task is to extract knowledge and transfer it into ~org-roam2~ "cards", as a sort of /"knowledge base"/.

Clear, concise, mathematically rigorous definitions of abstract concepts.

* The Architecture Of Complexity
This is, perhaps, the most important paper (for actually smart people).

The date is *1962*, so this is just 2 years after John McCarthy published his LISP paper for the first time.

All the fine people supposedly have read this, B. Liskov, Guy L. Steele, Gerald Sussman, P. Norvig, SPJ.

It has been written by a theoretician. Theoreticians, in general, does not care about precision and rigor, so every single assertion could be independently verified by anyone, but they sometimes have so-called "insights" and properly capture important generalities.

This short paper basically says that you have to design your program as a set of /layered embedded DSLs/, so it *will be* as robust as possible and *will be* developed /faster/, if one uses "bottom-up process" (/after/ "top-down" problem domain decomposition) in prototyping.

The notion of "stable intermediate forms" is, indeed, /universal/. So is the notion of /partitioning/ and of a /hierarchy of layers/, which is what a complex system decomposes into (atoms, molecules, aminoacids, proteins are obviously form distinct layers and have actual "abstraction barriers" at each level).

Another universal and fundamental notion in this short paper is of a /heuristic-based back-tracking search as a universal strategy of problem-solving/. He did not use these terms, but he talks abot "trial-and-error search process" and "/selectivity/ based on heuristics and rules of thumb".

This is exactly what happens in human societies. Instead of so-called "free will" individuals are just bouncing around within their social, economic and genetic /constraints/, trying this and that and "seeing what sticks".

But the "stable intermediate forms" (which are /reused/ (!) and your own data-types, functions, modules) and the layered architecture (of embedded DSLs) was a /revelation/.

LISP guys got it. They even got /homoiconicity/ from cell biology. Everything -- enzymes, which are just particularly folded proteins, and the "data" (other proteins) --  has been made from /sequences/ of the same 20 aminoacids.

The only thing that "missed" is the subtle notion from Haskell, where the monadic code /form actual membranes/ with "pumps" and "portals", and the I/O code (and other effects) tent to stay "at the edges".

/Every Monad defines and implicit abstraction barrier/ (using Kleisli arrows, which we call ~return~ or "lifting" in general), but his is another story, this time by me.

[[https://faculty.sites.iastate.edu/tesfatsi/archive/tesfatsi/ArchitectureOfComplexity.HSimon1962.pdf][The Architecture Of Complexity (Herbert A. Simon, 1962)]]

* Discrete-time signal processing (Alan V. Oppenheim)
The most dense books, but the fundamental concepts and proven techniques has to be extracted from them. The author is one of the pioneers in this field.

This, by the way, is the essence of learning -- to extract the right understanding from poorly or messy written books.

* Time series
Very difficult to find a definitive, concise well-written non-bullshit book.

My general heuristic is to look for something from the /MIT Press/ first.
